server:
  port: 8200

spring:
  application:
    name: cloud-gateway-zuulserver

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    status-page-url: http://192.168.1.7:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    
zuul:
  routes:
    producer:
      path: /pproducer/**
      serviceId: producer
  strip-prefix: true