server:
  port: 8082
spring:
  application:
    name: login
  redis:
    cluster:
      nodes: 192.168.1.23:7000,192.168.1.23:7001,192.168.1.23:7002,192.168.1.23:7003,192.168.1.23:7004,192.168.1.23:7005
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxcppt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: olmysoft
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    status-page-url: http://192.168.1.7:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

